version: "3"

services:
  symfony:
    container_name: bigbuy_back
    environment:
      - TZ=Europe/Madrid
      - DEBIAN_FRONTEND=noninteractive
    build:
      context: ./apache
    ports:
      - 80:80
    volumes:
      - ./web:/var/www/html
      - ./cron.d:/etc/cron.d
      - ./composer.www-data:/var/www/.composer
    networks:
      - bigbuy

  phpmyadmin:
    container_name: phpmyadmin-5.7
    image: phpmyadmin
    ports:
      - 12254:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOSTS=mysql
      - PMA_PORTS=3306
      - UPLOAD_LIMIT=2G
      - PMA_USER=root
      - PMA_PASSWORD=x8lE8xBWJoOz
    networks:
      - bigbuy

  mysql:
    container_name: mysql
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: x8lE8xBWJoOz
    volumes:
      - ./mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - bigbuy

networks:
  bigbuy:
